### ISSUE TITLE
Error - No Handler Registered

### ISSUE THREAD

**Issue by ndran** [stechstudio/laravel-ssh-tunnel#2]
Trying to test to see if my configuration is working and after running "php artisan tunneler:activate" its giving me the following error:

No handler registered for command [STS\Tunneler\Jobs\CreateTunnel]

I've registered the provider by adding "STS\Tunneler\TunnelerServiceProvider::class," into my providers array ( config/app.php ) 

Any ideas? The project I'm attempting to configure this with is running laravel 5.1

**Comment by bubba-h57** [comment]
The issue is that as of [Laravel 5.2.0](https://laravel.com/docs/5.3/upgrade#upgrade-5.2.0) 

> You no longer need to implement the SelfHandling contract on your jobs / commands. All jobs are now self-handling by default, so you can remove this interface from your classes.

I didn't write this taking into account the older (5.1) implementation needing the SelfHandling contract. So there are a couple of things.

I need to update the `readme.md` with the minimum version supported as 5.2 or greater.

You can actually still run this in 5.1 with a little duct-tape. You just need to change:

```
<?php namespace STS\Tunneler\Jobs;

class CreateTunnel 
{
```
to
```
<?php namespace STS\Tunneler\Jobs;

use Illuminate\Contracts\Bus\SelfHandling;

class CreateTunnel implements SelfHandling
{
```

**Comment by ndran** [comment]
Great! Thank you for the band-aid 👍 Lightning fast response time too!
